apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: guisousa/nginx-guizin:latest
          ports:
          - name: http-port
            containerPort: 80