apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http-port
      port: 80
      targetPort: 80
      nodePort: 32001
  selector:
    app: nginx-project