apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 8082
      targetPort: 80
  selector:
    app: nginx-project